export default [
  {
    title: "Title",
    descriptionText: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    image: ["/assets/images/picture/Audi_R8_01.jpg"],
    id: "bMokId",
    userName: "Figaro",
    userAvatar: "",
    userId: "u16f240474f0",
    createDate: "Fri Dec 20 2019 17:55:28 GMT+0200 (Eastern European Standard Time)",
    starRating: 0,
    currentLike: 0,
    currentVisibility: 0,
    new: false,
  },
  {
    title: "Title",
    descriptionText: "This 14 photos!!!!!!!!!!!!!Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    image: ["/assets/images/picture/Audi_R8_01.jpg", "/assets/images/picture/Audi_R8_02.jpg", "/assets/images/picture/Audi_S5.jpg", "/assets/images/picture/Audi_S5_.jpg", "/assets/images/picture/Big-dog-chopper.jpg", "/assets/images/picture/Bmw.jpg", "/assets/images/picture/Bmw_.jpg", "/assets/images/picture/Bmw_M3_E93.jpg", "/assets/images/picture/Bmw_M6.jpg", "/assets/images/picture/Camaro.jpg", "/assets/images/picture/Charger_Srt.jpg", "/assets/images/picture/Corvette.jpg", "/assets/images/picture/Custom_Hayabusa.jpg", "/assets/images/picture/Custom_Kawasaki.jpg"],
    id: "bMokId1",
    userName: "Figaro",
    userAvatar: "",
    userId: "u16f240474f1",
    createDate: "Fri Dec 20 2019 17:55:28 GMT+0200 (Eastern European Standard Time)",
    starRating: 0,
    currentLike: 0,
    currentVisibility: 0,
    new: false,
  },
  {
    title: "Title",
    descriptionText: "This zero photo!!!!!!!!Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    image: [],
    id: "bMokId2",
    userName: "Figaro",
    userAvatar: "",
    userId: "u16f240474f2",
    createDate: "Fri Dec 20 2019 17:55:28 GMT+0200 (Eastern European Standard Time)",
    starRating: 0,
    currentLike: 0,
    currentVisibility: 0,
    new: false,
  },
  {
    title: "Title",
    descriptionText: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    image: ["/assets/images/picture/Audi_R8_01.jpg", "/assets/images/picture/Audi_R8_02.jpg", "/assets/images/picture/Audi_S5.jpg", "/assets/images/picture/Audi_S5_.jpg", "/assets/images/picture/Big-dog-chopper.jpg", "/assets/images/picture/Bmw.jpg", "/assets/images/picture/Bmw_.jpg", "/assets/images/picture/Bmw_M3_E93.jpg", "/assets/images/picture/Bmw_M6.jpg", "/assets/images/picture/Camaro.jpg", "/assets/images/picture/Charger_Srt.jpg", "/assets/images/picture/Corvette.jpg", "/assets/images/picture/Custom_Hayabusa.jpg", "/assets/images/picture/Custom_Kawasaki.jpg"],
    id: "bMokId3",
    userName: "Figaro",
    userAvatar: "",
    userId: "u16f240474f3",
    createDate: "Fri Dec 20 2019 17:55:28 GMT+0200 (Eastern European Standard Time)",
    starRating: 0,
    currentLike: 0,
    currentVisibility: 0,
    new: false,
  },
  {
    title: "Title",
    descriptionText: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    image: ["/assets/images/picture/Audi_R8_01.jpg", "/assets/images/picture/Audi_R8_02.jpg", "/assets/images/picture/Audi_S5.jpg", "/assets/images/picture/Audi_S5_.jpg", "/assets/images/picture/Big-dog-chopper.jpg", "/assets/images/picture/Bmw.jpg", "/assets/images/picture/Bmw_.jpg", "/assets/images/picture/Bmw_M3_E93.jpg", "/assets/images/picture/Bmw_M6.jpg", "/assets/images/picture/Camaro.jpg", "/assets/images/picture/Charger_Srt.jpg", "/assets/images/picture/Corvette.jpg", "/assets/images/picture/Custom_Hayabusa.jpg", "/assets/images/picture/Custom_Kawasaki.jpg"],
    id: "bMokId4",
    userName: "Figaro",
    userAvatar: "",
    userId: "u16f240474f4",
    createDate: "Fri Dec 20 2019 17:55:28 GMT+0200 (Eastern European Standard Time)",
    starRating: 0,
    currentLike: 0,
    currentVisibility: 0,
    new: false,
  },
  {
    title: "Title",
    descriptionText: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    image: ["/assets/images/picture/Audi_R8_01.jpg", "/assets/images/picture/Audi_R8_02.jpg", "/assets/images/picture/Audi_S5.jpg", "/assets/images/picture/Audi_S5_.jpg", "/assets/images/picture/Big-dog-chopper.jpg", "/assets/images/picture/Bmw.jpg", "/assets/images/picture/Bmw_.jpg", "/assets/images/picture/Bmw_M3_E93.jpg", "/assets/images/picture/Bmw_M6.jpg", "/assets/images/picture/Camaro.jpg", "/assets/images/picture/Charger_Srt.jpg", "/assets/images/picture/Corvette.jpg", "/assets/images/picture/Custom_Hayabusa.jpg", "/assets/images/picture/Custom_Kawasaki.jpg"],
    id: "bMokId5",
    userName: "Figaro",
    userAvatar: "",
    userId: "u16f240474f5",
    createDate: "Fri Dec 20 2019 17:55:28 GMT+0200 (Eastern European Standard Time)",
    starRating: 0,
    currentLike: 0,
    currentVisibility: 0,
    new: false,
  },
  {
    title: "Title",
    descriptionText: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    image: ["/assets/images/picture/Audi_R8_01.jpg", "/assets/images/picture/Audi_R8_02.jpg", "/assets/images/picture/Audi_S5.jpg", "/assets/images/picture/Audi_S5_.jpg", "/assets/images/picture/Big-dog-chopper.jpg", "/assets/images/picture/Bmw.jpg", "/assets/images/picture/Bmw_.jpg", "/assets/images/picture/Bmw_M3_E93.jpg", "/assets/images/picture/Bmw_M6.jpg", "/assets/images/picture/Camaro.jpg", "/assets/images/picture/Charger_Srt.jpg", "/assets/images/picture/Corvette.jpg", "/assets/images/picture/Custom_Hayabusa.jpg", "/assets/images/picture/Custom_Kawasaki.jpg"],
    id: "bMokId6",
    userName: "Figaro",
    userAvatar: "",
    userId: "u16f240474f6",
    createDate: "Fri Dec 20 2019 17:55:28 GMT+0200 (Eastern European Standard Time)",
    starRating: 0,
    currentLike: 0,
    currentVisibility: 0,
    new: false,
  },
  {
    title: "Title",
    descriptionText: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    image: ["/assets/images/picture/Audi_R8_01.jpg", "/assets/images/picture/Audi_R8_02.jpg", "/assets/images/picture/Audi_S5.jpg", "/assets/images/picture/Audi_S5_.jpg", "/assets/images/picture/Big-dog-chopper.jpg", "/assets/images/picture/Bmw.jpg", "/assets/images/picture/Bmw_.jpg", "/assets/images/picture/Bmw_M3_E93.jpg", "/assets/images/picture/Bmw_M6.jpg", "/assets/images/picture/Camaro.jpg", "/assets/images/picture/Charger_Srt.jpg", "/assets/images/picture/Corvette.jpg", "/assets/images/picture/Custom_Hayabusa.jpg", "/assets/images/picture/Custom_Kawasaki.jpg"],
    id: "bMokId7",
    userName: "Figaro",
    userAvatar: "",
    userId: "u16f240474f7",
    createDate: "Fri Dec 20 2019 17:55:28 GMT+0200 (Eastern European Standard Time)",
    starRating: 0,
    currentLike: 0,
    currentVisibility: 0,
    new: false,
  },
  {
    title: "Title",
    descriptionText: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    image: ["/assets/images/picture/Audi_R8_01.jpg", "/assets/images/picture/Audi_R8_02.jpg", "/assets/images/picture/Audi_S5.jpg", "/assets/images/picture/Audi_S5_.jpg", "/assets/images/picture/Big-dog-chopper.jpg", "/assets/images/picture/Bmw.jpg", "/assets/images/picture/Bmw_.jpg", "/assets/images/picture/Bmw_M3_E93.jpg", "/assets/images/picture/Bmw_M6.jpg", "/assets/images/picture/Camaro.jpg", "/assets/images/picture/Charger_Srt.jpg", "/assets/images/picture/Corvette.jpg", "/assets/images/picture/Custom_Hayabusa.jpg", "/assets/images/picture/Custom_Kawasaki.jpg"],
    id: "bMokId8",
    userName: "Figaro",
    userAvatar: "",
    userId: "u16f240474f8",
    createDate: "Fri Dec 20 2019 17:55:28 GMT+0200 (Eastern European Standard Time)",
    starRating: 0,
    currentLike: 0,
    currentVisibility: 0,
    new: false,
  },
  {
    title: "Title",
    descriptionText: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    image: ["/assets/images/picture/Audi_R8_01.jpg", "/assets/images/picture/Audi_R8_02.jpg", "/assets/images/picture/Audi_S5.jpg", "/assets/images/picture/Audi_S5_.jpg", "/assets/images/picture/Big-dog-chopper.jpg", "/assets/images/picture/Bmw.jpg", "/assets/images/picture/Bmw_.jpg", "/assets/images/picture/Bmw_M3_E93.jpg", "/assets/images/picture/Bmw_M6.jpg", "/assets/images/picture/Camaro.jpg", "/assets/images/picture/Charger_Srt.jpg", "/assets/images/picture/Corvette.jpg", "/assets/images/picture/Custom_Hayabusa.jpg", "/assets/images/picture/Custom_Kawasaki.jpg"],
    id: "bMokId9",
    userName: "Figaro",
    userAvatar: "",
    userId: "u16f240474f9",
    createDate: "Fri Dec 20 2019 17:55:28 GMT+0200 (Eastern European Standard Time)",
    starRating: 0,
    currentLike: 0,
    currentVisibility: 0,
    new: false,
  },
]